worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /opt/nginx/conf/mime.types;
    default_type application/octet-stream;

    upstream ppc_webservice {
    server 127.0.0.1:8000;
    keepalive 32;
    }

server {
    listen 80;
    server_name _;

    # 前端页面目录（按你的实际目录改）
    root /opt/nginx/html;
    index index.html;

    # 静态资源不存在就返回404， 不要回退到 index.html
    location /assets/ {
	try_files $uri =404;
    }

    # 前端路由（若是 Vue/React SPA）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 反向代理配置（解决跨域，转发API请求）
    location /emsApi/ {
	proxy_pass http://127.0.0.1:8000/; #web服务监听ip+端口
	
	# 一下配置防止后端获取不到真实的IP或Host
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;

	proxy_connect_timeout 5s;
	proxy_send_timeout 30s;
	proxy_read_timeout 30s;
    }
}
}
